-- Oria: per-section AI memories.
--
-- A section "memory" is a short fact, preference, or pattern the user has
-- saved (or explicitly accepted) for one section. The section-scoped Ask
-- assistant reads them as context and the classifier consults them when
-- placing similar uploads. Memories are scoped tightly:
--
--   • organization_id      — never cross spaces
--   • plus exactly one of:
--       builtin_section    — for built-in sections (finance, travel, …)
--       custom_section_id  — for user-created sections
--       smart_section      — for the Diet / Bills smart sections
--
-- source captures how the memory was created:
--   'user'         — typed by hand
--   'pattern'      — generated by a future pattern detector
--   'confirmation' — user accepted a "Should I remember this?" prompt
--
-- Idempotent. Safe to re-run.

create table if not exists public.section_memories (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,

  -- Section ref (exactly one is set, enforced by the check below).
  builtin_section public.section,
  custom_section_id uuid references public.custom_sections(id) on delete cascade,
  smart_section text,

  content text not null,
  source text not null default 'user',

  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  -- Exactly one of the three section refs must be set.
  check (
    (builtin_section is not null)::int +
    (custom_section_id is not null)::int +
    (smart_section is not null)::int = 1
  ),
  check (source in ('user', 'pattern', 'confirmation')),
  check (smart_section is null or smart_section in ('diet', 'bills'))
);

-- One row per (org, section, content) to avoid duplicate "save" clicks.
create unique index if not exists section_memories_builtin_unique
  on public.section_memories(organization_id, builtin_section, content)
  where deleted_at is null and builtin_section is not null;
create unique index if not exists section_memories_custom_unique
  on public.section_memories(organization_id, custom_section_id, content)
  where deleted_at is null and custom_section_id is not null;
create unique index if not exists section_memories_smart_unique
  on public.section_memories(organization_id, smart_section, content)
  where deleted_at is null and smart_section is not null;

create index if not exists section_memories_org_idx
  on public.section_memories(organization_id, created_at desc)
  where deleted_at is null;

drop trigger if exists section_memories_touch on public.section_memories;
create trigger section_memories_touch before update on public.section_memories
  for each row execute function public.touch_updated_at();

alter table public.section_memories enable row level security;

drop policy if exists "section_memories_read_members" on public.section_memories;
create policy "section_memories_read_members"
  on public.section_memories for select
  using (
    deleted_at is null
    and public.is_org_member(organization_id)
  );

drop policy if exists "section_memories_insert_members" on public.section_memories;
create policy "section_memories_insert_members"
  on public.section_memories for insert
  to authenticated
  with check (
    public.is_org_member(organization_id)
    and (created_by is null or created_by = auth.uid())
  );

drop policy if exists "section_memories_update_members" on public.section_memories;
create policy "section_memories_update_members"
  on public.section_memories for update
  using (public.is_org_member(organization_id))
  with check (public.is_org_member(organization_id));

drop policy if exists "section_memories_delete_members" on public.section_memories;
create policy "section_memories_delete_members"
  on public.section_memories for delete
  using (public.is_org_member(organization_id));

notify pgrst, 'reload schema';
