import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import {
  VOICE_RULES,
  BANNED_PHRASES,
  EM_DASH,
  findBannedPhrases,
  sweepEmDash,
} from "@/lib/voice/oria-voice";

/**
 * F3(a) anti-slop. The canonical voice block bans a list of phrases and the
 * em-dash; findBannedPhrases is the guard. This test pins the guard's behavior
 * AND scans the live samples generated for this round (docs/voice/round-14_7-
 * samples.md) so a regression that lets slop through fails the build, no API key
 * required.
 */

describe("findBannedPhrases", () => {
  it("flags an em-dash", () => {
    expect(findBannedPhrases("Renews March 14 — $695")).toContain("em-dash (U+2014)");
  });

  it("flags slop phrases and hype words, case-insensitively", () => {
    expect(findBannedPhrases("I'd be happy to help with that")).toContain("I'd be happy to");
    expect(findBannedPhrases("Feel free to reach out")).toContain("Feel free to");
    expect(findBannedPhrases("This seamless, game-changing tool")).toEqual(
      expect.arrayContaining(["game-changing", "seamless"]),
    );
    expect(findBannedPhrases("CERTAINLY! let's dive in")).toEqual(
      expect.arrayContaining(["Certainly!", "Let's dive in"]),
    );
  });

  it("passes a clean Oria answer", () => {
    const clean =
      "Your AmEx Platinum renews March 14, $695. The Apple News+ benefit covers it for 8 months if you use it. You don't.";
    expect(findBannedPhrases(clean)).toEqual([]);
  });

  it("does not flag domain-legitimate words left out of the hard list", () => {
    // "leverage" (investor noun) and "unlock" (a benefit that unlocks) are
    // deliberately not in the hard gate; they must not be flagged.
    expect(findBannedPhrases("Your leverage ratio is 1.4x")).toEqual([]);
    expect(findBannedPhrases("The lounge benefit unlocks at $200 spend")).toEqual([]);
  });
});

describe("sweepEmDash", () => {
  it("replaces the em-dash with a comma and tidies spacing", () => {
    expect(sweepEmDash("Renews March 14 — $695")).toBe("Renews March 14, $695");
  });
  it("leaves clean text untouched", () => {
    expect(sweepEmDash("Renews March 14, $695")).toBe("Renews March 14, $695");
  });
});

describe("VOICE_RULES integrity", () => {
  it("contains no em-dash (it would mirror back into model output)", () => {
    expect(VOICE_RULES.includes(EM_DASH)).toBe(false);
  });
  it("is non-trivial and names the voice", () => {
    expect(VOICE_RULES.length).toBeGreaterThan(500);
    expect(VOICE_RULES).toContain("second person");
  });
  it("exports a non-empty banned list", () => {
    expect(BANNED_PHRASES.length).toBeGreaterThan(10);
  });
});

describe("the live Round 14.7 samples are slop-free", () => {
  const file = join(process.cwd(), "docs", "voice", "round-14_7-samples.md");

  it("the samples file exists (generated by scripts/voice-samples.mts)", () => {
    expect(existsSync(file)).toBe(true);
  });

  it("contains zero banned phrases and zero em-dashes across every output", () => {
    const text = readFileSync(file, "utf8");
    const hits = findBannedPhrases(text);
    expect(hits, `slop in samples file: ${hits.join(", ")}`).toEqual([]);
  });

  it("records that no SLOP markers were written during generation", () => {
    const text = readFileSync(file, "utf8");
    expect(text.includes("> SLOP:")).toBe(false);
    expect(text).toContain("Total banned-phrase hits across all live outputs: 0.");
  });
});
